# https://hub.docker.com/_/postgres
# https://docs.docker.com/guides/postgresql/#docker-compose-configuration

services:
  db:
    image: postgres:18
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      # - ./db_init:/docker-entrypoint-initdb.d   # add .sql schema files to ./db_init/

volumes:
  pgdata:
