services:
  db:
    image: postgres:18
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"   # host port is set in .env, container port is always 5432
    volumes:
      - pgdata:/var/lib/postgresql
      # - ./db_init:/docker-entrypoint-initdb.d   # add .sql schema files to ./db_init/

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:


### =================== REFERENCES ===================
# https://docs.docker.com/guides/postgresql/#docker-compose-configuration
# https://docs.docker.com/reference/compose-file/services
# https://docs.docker.com/compose/how-tos/networking
# https://hub.docker.com/_/postgres
# https://hub.docker.com/_/python

### =================== AUTHOR ===================
# Luke Mitchell, 2026
